name: .NET Build on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.401
    - name: Setup Windows SDK 10.0.18362.0
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      with:
        sdk-version: 18362
    - name: Build and Pack
      run: |
        dotnet build Material.Icons -c Release /p:Platform="Any CPU"
        dotnet build Material.Icons.WPF -c Release /p:Platform="Any CPU"
        dotnet build Material.Icons.Avalonia -c Release /p:Platform="Any CPU"
        dotnet build Material.Icons.WinUI3 -c Release /p:Platform="Any CPU"
