name: .NET Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Build and Pack
      run: |
        dotnet build Material.Icons
        dotnet build Material.Icons.WPF
        dotnet build Material.Icons.Avalonia
    - name: Publish to Nuget
      run: |
        dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push **/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/SKProCH/index.json --skip-duplicate
