name: Icons collection update

on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Run generator project
        run: dotnet build Material.Icons
      - name: Check if there changes
        id: state
        run: |
          [[ -v $(git status -s) ]]
          echo '::set-output name=diff::'$(echo $?)
      - name: Read version
        if: steps.state.outputs.diff == 0
        id: getversion
        run: echo '::set-output name=version::'$(grep '(?<=<Version>).*(?=<\/Version>)' Material.Icons/Material.Icons.csproj -P -o)
      - name: Upgrade version
        if: steps.state.outputs.diff == 0
        id: bsv
        uses: jessicalostinspace/bump-semantic-version-action@v1.0.1
        with:
          semantic-version: ${{steps.getversion.outputs.version}}
          version-type: 'PATCH'
      - name: Write version
        if: steps.state.outputs.diff == 0
        run: sed -i 's/<Version>${{steps.getversion.outputs.version}}/<Version>${{steps.bsv.outputs.bumped-semantic-version}}/' Material.Icons/Material.Icons.csproj
      - name: Commit and push
        if: steps.state.outputs.diff == 0
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          message: 'Icons collection update'
