name: Icons collection update

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run generator project
        run: nuke GhUpdateIconsWorkflow
      - name: Push changes (if any)
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            message: 'Icons collection update ✨'
            branch: 'master'            
